## ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!

## fastq input file data ##
fastqDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/star/fastqs/"
# hisat2 genome index location #
StarIndexDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/StarIndexDir/"

# star 1stpass output directory #
Star1stPassOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/Star1stpass/"

# star 1stpass output directory #
Star2ndPassOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/Star2ndpass/"

# sortsam output directory # 
samsortOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/Star/sorted_bams/"
