## ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!
#
########################
## RNA-SEQ FASTQ FILES #
########################
# fastq input file data ##
fastqDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/fastq/drosophila_melanogaster/trimmed_reads/"

############
## HISAT2 ##
############
# Hisat2 index info #
Hisat2IndexDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/genomes/dmel/hisat/"
Hisat2IndexPrefix: "dmel_GCF_000001215.4_Release_6_hisat2"

# hisat2 output directory #
Hisat2Outdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/hisat/dmel/"

# sortsam output directory # 
Hisat2SamsortOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/hisat/dmel/sorted/"

##########
## STAR ##
#########
# star genome index location #
StarIndexDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/genomes/dmel/star/"

# star 1stpass output directory #
Star1stPassOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/star/dmel/Star1stpass/"

# star 1stpass output directory #
Star2ndPassOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/star/dmel/Star2ndpass/"

# STAR sortsam output directory # 
StarSamsortOutdir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/star/dmel/sorted_bams/"


###############
## STRINGTIE ##
###############
# directory where input bam files are located #
StringtieBamDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/hisat/dmel/sorted/"

# alignment tool used to produce bams #
StringtieAlignmentTool: "hisat2"

# output directory for sample-level stringtie assemblies #
StringtieAssemblyDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/stringtie/dmel/individual_assemblies/"

# merged assembly directory #
StringtieMergeDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/stringtie/dmel/merged_assembly/"
StringtieMergeLabel: "dmel" 

##############
##  SCALLOP ##
#############
ScallopAlignmentTool: "hisat2"
ScallopAssemblyDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/scallop/dmel/hisat2/individual_assemblies/"
TacoDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/scallop/dmel/hisat2/taco/"
