## ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!

# LABEL FOR MERGED ASSEMBLIES #
speciesname: "dmel"

########################
## RNA-SEQ FASTQ FILES #
########################
# fastq input file data ##
fastqDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/fastq/drosophila_melanogaster/trimmed_reads/"

############
## HISAT2 ##
############
Hisat2IndexDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/genomes/dmel/hisat/"
Hisat2IndexPrefix: "dmel_GCF_000001215.4_Release_6_hisat2"
Hisat2Outdir: "hisat2/"
Hisat2SamsortOutdir: "hisat2/sorted/" 

##########
## STAR ##
#########
StarIndexDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/diptera/genomes/dmel/star/"
Star1stPassOutdir: "star/star1stpass/" 
Star2ndPassOutdir: "star/star2ndpass/"
StarSamsortOutdir: "star/sorted/" 

#############
# STRINGTIE #
# ###########

StringtieHisat2AssemblyDir: "stringtie/hisat2/individual_assemblies/" 
StringtieHisat2MergeDir: "stringtie/hisat2/merged_assembly/" 
StringtieStarAssemblyDir: "stringtie/star/individual_assemblies/"
StringtieStarMergeDir: "stringtie/star/merged_assembly/"

##############
##  SCALLOP ##
#############
ScallopHisat2Dir: "scallop/hisat2/"
ScallopHisat2AssemblyDir: "scallop/hisat2/individual_assemblies/" 
TacoHisat2Dir: "scallop/hisat2/taco/"
ScallopStarDir: "scallop/star/"
ScallopStarAssemblyDir: "scallop/star/individual_assemblies/"
TacoStarDir: "scallop/star/taco/" 
