__default__:
    partition: "shared"
    time: 720
    nodes: 1
    output: "logs/slurm-%j.out"
    error: "logs/slurm-%j.err"


#############
# stringtie #
############


stringtie:
    partition: "holy-info,holy-smokes,holy-cow,shared" 
    output: "logs/stringtie-%j.out"
    error: "logs/stringtie-%j.err"
    job-name: "stringtie"

merge:
    partition: "holy-info,holy-smokes,holy-cow,shared"
    output: "logs/stringtie-merge-%j.out"
    error: "logs/stringtie-merge-%j.err"
    job-name: "stie-merge"

###########
# hisat2 #
###########

hisat2_align:
    partition: "holy-info,holy-smokes,holy-cow,shared"
    output: "logs/hisat2-%j.out"
    error: "logs/hisat2-%j.err"
    job-name: "hisat2"

samsort:
    partition: "holy-info,holy-smokes,holy-cow,shared"
    output: "logs/samsort-%j.out"
    error: "logs/samsort-%j.err"
    job-name: "samsort"
