__default__:
    partition: "shared"
    time: 720
    nodes: 1
    output: "logs/slurm-%j.out"
    error: "logs/slurm-%j.err"


###
# stringtie
###

stringtie:
    partition: "holy-info,holy-smokes,holy-cow,shared" 
    output: "logs/stringtie-%j.out"
    error: "logs/stringtie-%j.err"
    job-name: "stringtie"

###
# stringtie-merge
# ###

merge:
    partition: "holy-info,holy-smokes,holy-cow,shared"
    output: "logs/stringtie-merge-%j.out"
    error: "logs/stringtie-merge-%j.err"
    job-name: "stie-merge"
