## ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!

# directory where input bam files are located #
bamDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/stringtie/input_bams/"

# alignment tool used to produce bams #
alignment_tool: "hisat2"

# output directory for sample-level stringtie assemblies #
assemblyDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/stringtie/individual_assemblies/"

# merged assembly directory #
mergeDir: "/n/holyscratch01/informatics/genome_annotation_evaluation/snakemake/stringtie/merged_assembly/"
mergeLabel: "dple" 
